name: 'Chromatic Staging'
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          yarn
      - run: |
          yarn build
      - run: |
          yarn build-storybook
      - uses: chromaui/action@v1
        env:
          CHROMATIC_INDEX_URL: https://www.staging-chromatic.com
        with:
          appCode: mj0nvsrz1ja
          token: ${{ secrets.GITHUB_TOKEN }}
          storybookBuildDir: storybook-static
